### ISSUE TITLE
Problem with the documentation

### ISSUE THREAD

**Issue by Vincent14** [Pobb/docket#4]
Hello, a friend of me has got a problème while installing Docket, Docker in your pocket. He juste followed la doc, et there is a mistake on this line: 

> $ alias docket="'/bin/bash docket.sh'"

It seems that the correct alias would be:

> $ alias docket="/bin/bash docket.sh"

Yes, the single quotes are en trop :)

**Comment by Pobb** [comment]
README edited, thanx for your support !
